### ISSUE TITLE
step 3 of install does not work ./build.sh

### ISSUE THREAD

**Issue by prepstarr** [etcd-io/website#594] opened 2022-07-05 04:19 UTC
step 3 of the installation instructions from build from source instructions : https://etcd.io/docs/v3.5/install/

the error is as follows : 

```
sixpiece@Chalin:~/etcd$ ./build.sh
./scripts/test_lib.sh: ligne 5: go : commande introuvable
must be run from 'go.etcd.io/etcd/v3' module directory
```

**Comment by spzala** [comment] 2022-07-18 19:42
@prepstarr which etcd branch are you using? how did you clone the repo?

**Comment by AustinBenoit** [comment] 2022-07-20 23:11
@prepstarr If you have checked out the latest main branch then you build with `$ ./scripts/build.sh`. The latest alpha build documentation is available: [https://etcd.io/docs/v3.6/install/](https://etcd.io/docs/v3.6/install/)

**Comment by prepstarr** [comment] 2022-08-07 18:27
I think I did it from debian... I'm going to check now...

**Comment by prepstarr** [comment] 2022-08-07 18:31
> @prepstarr which etcd branch are you using? how did you clone the repo?

yes I cloned it , I am not sure how to know what version... I will try to update to the latest.

**Comment by jmhbnz** [comment] 2023-05-10 00:34
Hi @prepstarr - Can we close this one now? I'm unable to reproduce an issue when following the build from source instructions for either 3.5 or 3.6.  Please let us know, thanks 🙏🏻

**Closed** 2023-12-17 09:47 UTC
